language: python

python:
  - "3.6"

os:
  - linux
  - windows

cache: pip3

services:
  - docker

before_install:
  - docker pull ubuntu
  - docker build -t docker_1 .


# Установка фактически разбита на два этапа: 
# 1) python3 setup.py sdist создаёт архив, который заливается (руками) на dropbox
# 2) из dropbox архив автоматически скачивается и устанавливается во время создания 
# docker-контейнера

install:
  - pip3 install pyyaml
  - pip3 install pytest

script:
  - cd tests/SmartHouseTests-1.0.0
  - pytest ../SmartHouseTests-1.0.0/

branches:
  only:
    - master
    - dgk
    - sergey
    - timur
