# Эскиз самой предварительной версии из всех возможных

language: python

python:
  - "3.7"

os:
  - linux
  - windows

cache: pip3

services:
  - docker

before_install:
  - docker pull ubuntu
  - docker run [params] <repository_name> [params] server /bin/bash


install:
    - pip3 install <?> 
# Установка фактически разбита на два этапа: 
# 1) python3 setup.py sdist создаёт архив, который заливается (руками) на dropbox
# 2) из dropbox архив автоматически скачивается и устанавливается во время создания 
# docker-контейнера

script:
  - tests.py [??]

branches:
  only:
    - master
